version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: deckdoctor_postgres
    restart: always
    environment:
      POSTGRES_USER: deckuser
      POSTGRES_PASSWORD: deckpass
      POSTGRES_DB: deckdoctor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: deckdoctor_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: